(Feat) : Added Cancel button when editing project details from Dashboard
StatTag/StatWrap pull request #207
Opened 2024-05-31 21:15 UTC by Abhijay007

# Summary of Changes

This pull request aims to enhance the user experience when editing project details in StatWrap by adding a "Cancel" button that allows users to discard any changes made and revert to the original view.

**Changes:**

- Added a "Cancel" button to the right of the "Save Details" button.
- Implemented functionality to discard any edits when the "Cancel" button is clicked.
- Added a prompt to alert users if they have unsaved changes when they click "Cancel", asking "You have made changes. Do you wish to discard those changes?"
- Ensured that clicking "Cancel" exits the editing interface and returns the user to the Dashboard view.

## Related Issue

Closes #167 

## Checklist

- [x] My code is well-documented, and I've updated relevant documentation.
- [x] I have tested these changes on my local environment.
- [x] I have reviewed and proofread my code and the changes.
- [x] The branch is up-to-date with the base branch.

## Additional Context

https://github.com/StatTag/StatWrap/assets/64387054/7838c50d-856d-4f84-83ef-87dcae5527ef

## Reviewer(s)

@lrasmus

2024-06-01 08:36 UTC, AdiAkhileshSingh15 commented
Just reviewed the changes, and they all seem quite relevant.

2024-06-03 21:25 UTC, lrasmus requested changes
It looks like there is an issue with it preserving the initialState as whatever project details are loaded the first time you edit a project.  I am running into an issue in the following scenario:

1. I have StatWrap configured with multiple projects available
2. I select sw-test2 from the list, and click "Edit Details"
![image](https://github.com/StatTag/StatWrap/assets/967970/09482ad9-cd89-47f2-8f3f-d7ae511d32a1)
3. I make no changes, and immediately click "Cancel".  The system works as designed, and does not prompt me about unsaved changes (there are none).
![image](https://github.com/StatTag/StatWrap/assets/967970/7561dff6-2756-4f09-84eb-708ff3c5aa27)
4. I select sw-test1 from the list, and click on "Edit Details"
![image](https://github.com/StatTag/StatWrap/assets/967970/b73f87e7-c219-4882-92e5-34d20b57d9cb)
5. I make no changes, and immediately click "Cancel".  The system prompts me to discard changes, even though no changes were made.
![image](https://github.com/StatTag/StatWrap/assets/967970/c16563bf-2da1-4e0b-a738-177af07941cc)
6. When I say "Yes" to discard the changes, although I have sw-test1 selected in the list of projects, it is displaying the project details for sw-test2.
![image](https://github.com/StatTag/StatWrap/assets/967970/b7d64162-57a1-4bfb-8137-de3475724dbf)

2024-06-03 21:25 UTC, lrasmus commented on app/components/Project/About/About.css
> +  float: left;
This is causing the "Edit Details" button to display on a separate line from the tags:
![image](https://github.com/StatTag/StatWrap/assets/967970/ce888159-eee1-47b9-84ef-fdd5ffd1a8e4)

We had wanted that all on one line to save whitespace, but open to discussion if you think there's a reason to keep them separated.
![image](https://github.com/StatTag/StatWrap/assets/967970/54b46d71-363b-4f30-84dd-5c1896139132)

2024-06-03 21:25 UTC, lrasmus commented
@Abhijay007 - thank you so much for the work on this!  Please see the two issues I noted: one related to layout, the other one more about functionality.  Thank you!

2024-06-04 06:21 UTC, Abhijay007 commented
> @Abhijay007 - thank you so much for the work on this! Please see the two issues I noted: one related to layout, the other one more about functionality. Thank you!

Thanks for the review @lrasmus I will look into the suggested points and make the changes accordingly

2024-06-04 11:54 UTC, lrasmus commented
> Thanks for the review @lrasmus I will look into the suggested points and make the changes accordingly

Thank you!!!  Sorry I didn't have time to dig in more myself.

2024-06-18 02:59 UTC, lrasmus approved these changes
Changes all look good and everything works great in my testing.  Thank you!

2024-06-18 03:00 UTC, merged